/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GuestBookTapHandler")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class GuestBookTapHandler : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "19a80e71fee4bbe44abbb9a616f8c1ca";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public UnityEngine.GameObject m_GuestBookListObject = default;

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), m_GuestBookListObject),
            };
        }
    }
}

#endif
