/*

    Copyright (c) 2024 Pocketz World. All rights reserved.

    This is a generated file, do not edit!

    Generated by com.pz.studio
*/

#if UNITY_EDITOR

using System;
using System.Linq;
using UnityEngine;
using Highrise.Client;

namespace Highrise.Lua.Generated
{
    [AddComponentMenu("Lua/GuestbookScreen")]
    [LuaBehaviourScript(s_scriptGUID)]
    public class GuestbookScreen : LuaBehaviourThunk
    {
        private const string s_scriptGUID = "c9b6eb5b2ec604b4db4cb7cca252cbc7";
        public override string ScriptGUID => s_scriptGUID;

        [SerializeField] public System.String m_fullText = "Hello {{user}},\n\nWelcome to our community! We're excited to have you here. Dive in, experiment, and enjoy all the possibilities. Leave your mark in our guest book and share your thoughts with us.\n\nHappy exploring!";

        protected override SerializedPropertyValue[] SerializeProperties()
        {
            if (_script == null)
                return Array.Empty<SerializedPropertyValue>();

            return new SerializedPropertyValue[]
            {
                CreateSerializedProperty(_script.GetPropertyAt(0), null),
                CreateSerializedProperty(_script.GetPropertyAt(1), null),
                CreateSerializedProperty(_script.GetPropertyAt(2), null),
                CreateSerializedProperty(_script.GetPropertyAt(3), m_fullText),
            };
        }
    }
}

#endif
